---
- name: Create systemd-networkd configuration files
  vars:
    all_files:
      - type: link
        files: "{{ systemd_networkd_link | dict2items }}"
      - type: netdev
        files: "{{ systemd_networkd_netdev | dict2items }}"
      - type: network
        files: "{{ systemd_networkd_network | dict2items }}"
  ansible.builtin.template:
    src: "systemd_networkd_config.j2"
    dest: "/etc/systemd/network/{{ item.1.key }}.{{ item.0.type }}"
    owner: root
    group: systemd-network
    mode: "0640"
  loop: "{{ query('subelements', all_files, 'files') }}"
  loop_control:
    label: "type: {{ item.0.type }}, name: {{ item.1.key }}"
  notify:
    - Reboot
    - Restart systemd-networkd

- name: Create nsswitch configuration
  become: true
  ansible.builtin.template:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    owner: root
    group: root
    mode: "0644"
  when: systemd_networkd_manage_nsswitch_config | bool
