---
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Install systemd-networkd packages
  ansible.builtin.package:
    name: "{{ systemd_networkd_packages }}"

- name: Import cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when: systemd_networkd_cleanup | bool

- name: Import configuration tasks
  ansible.builtin.import_tasks: config.yml

- name: Disable NetworkManager service
  ansible.builtin.service:
    name: NetworkManager
    state: stopped
    enabled: false
  failed_when: disable_nm_service.failed | bool and 'Could not find the requested service' not in disable_nm_service.msg
  register: disable_nm_service

- name: Disable network service
  ansible.builtin.service:
    name: network
    state: stopped
    enabled: false
  failed_when: disable_network_service.failed | bool and 'Could not find the requested service' not in disable_network_service.msg
  register: disable_network_service

- name: Remove netplan symlink
  ansible.builtin.file:
    path: /usr/lib/systemd/system-generators/netplan
    state: absent

- name: Disable netplan service
  ansible.builtin.file:
    path: /usr/sbin/netplan
    mode: '0644'
  failed_when: disable_np_service.failed | bool and 'is absent' not in disable_np_service.msg
  register: disable_np_service

- name: Enable and start systemd-networkd service
  ansible.builtin.service:
    name: systemd-networkd
    enabled: true
  when: systemd_networkd_network is defined or systemd_networkd_link is defined or systemd_networkd_netdev is defined

- name: Install systemd-resolved package
  ansible.builtin.package:
    name: systemd-resolved
  when: ansible_os_family == 'RedHat' and systemd_networkd_enable_resolved | bool

- name: Enable and start systemd-resolved service
  ansible.builtin.service:
    name: systemd-resolved
    enabled: true
    state: started
  when: systemd_networkd_enable_resolved | bool

- name: Replace /etc/resolv.conf with a symlink to the systemd-resolved {{ systemd_networkd_resolv_conf }}
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: "/run/systemd/resolve/{{ systemd_networkd_resolv_conf }}"
    state: link
    force: true
  when: systemd_networkd_symlink_resolv_conf | bool

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
