namespace: fitbeard
name: general
version: 1.0.0 # injected dynamically when publishing
readme: README.md
authors:
  - Tadas Sutkaitis <tadasas@gmail.com>
description: Set of Ansible roles, playbooks and modules for general purpose use.
license:
  - GPL-3.0-or-later
dependencies:
  ansible.posix: ">=1.3.0"
  community.crypto: ">=2.2.3"
  community.general: ">=4.5.0"
repository: https://github.com/fitbeard/ansible-collection-general
homepage: https://github.com/fitbeard/ansible-collection-general
issues: https://github.com/fitbeard/ansible-collection-general
build_ignore:
  - .github
  - .vscode
  - ansible-cache
  - molecule
  - .ansible-lint
  - .gitignore
  - .markdownlint.yml
  - .python-version
  - .pre-commit-config.yaml
  - poetry.lock
  - pyproject.toml
tags:
  - infrastructure
  - linux
  - networking
  - tools
