---
packer_version: 1.11.2
packer_archive_checksums:
  amd64:
    1.11.2: ced13efc257d0255932d14b8ae8f38863265133739a007c430cae106afcfc45a
packer_download_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_{{ ansible_facts['system'] | lower }}_{{ download_artifact_goarch }}.zip" # noqa: yaml[line-length]
packer_download_dest: "{{ download_artifact_work_directory }}/packer-{{ packer_version }}.zip"
packer_archive_checksum: "{{ packer_archive_checksums[download_artifact_goarch][packer_version] }}"
