---
- name: Reboot
  ansible.builtin.include_tasks: reboot.yml
  when:
    - reboot_required | default(false) | bool

- name: Restart systemd-networkd
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
  when: systemd_networkd_apply_config | bool
