---
- name: Install tuned package
  ansible.builtin.package:
    name: tuned

- name: Enable Tuned
  ansible.builtin.systemd:
    name: tuned
    state: started
    enabled: true

- name: Copy tuned service config
  ansible.builtin.template:
    src: tuned.service.j2
    dest: /etc/systemd/system/tuned.service
    mode: "0o644"
  notify: Reload tuned

- name: Copy tuned-main.conf
  ansible.builtin.template:
    src: tuned-main.conf.j2
    dest: /etc/tuned/tuned-main.conf
    mode: "0o644"
  notify: Reload tuned

- name: Get active tuned profile
  ansible.builtin.command: /usr/sbin/tuned-adm active
  register: tuned_active
  changed_when: false
  ignore_errors: true

- name: Create profile directory
  ansible.builtin.file:
    path: "/etc/tuned/{{ item }}"
    state: directory
    mode: "0o755"
  with_list: "{{ tuned_custom_profiles }}"
  when: tuned_custom_profiles is defined

- name: Create profile configs
  ansible.builtin.template:
    src: "{{ tuned_custom_profiles_source_path }}/{{ item }}.j2"
    dest: "/etc/tuned/{{ item }}/tuned.conf"
    mode: "0o644"
  with_list: "{{ tuned_custom_profiles }}"
  when: tuned_custom_profiles is defined
  register: profile_config

- name: Set active tuned profile {{ tuned_active_profile }}
  ansible.builtin.command: tuned-adm profile {{ tuned_active_profile }}
  when: tuned_active_profile not in tuned_active.stdout or profile_config.changed
  tags:
    - skip_ansible_lint
