name: publish

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  ansible-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build and publish collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.ANSIBLE_GALAXY_API_KEY }}"
