---
systemd_networkd_link: {}
systemd_networkd_netdev: {}
systemd_networkd_network: {}

systemd_networkd_apply_config: false

systemd_networkd_enable_resolved: false
systemd_networkd_symlink_resolv_conf: false
systemd_networkd_resolv_conf: "resolv.conf" # stub-resolv.conf or resolv.conf

systemd_networkd_cleanup: true
systemd_networkd_cleanup_patterns: []
systemd_networkd_cleanup_patterns_use_regex: false

systemd_networkd_primary_ip: "{{ ansible_default_ipv4.address }}"

systemd_networkd_manage_nsswitch_config: false
systemd_networkd_nsswitch_passwd: "files systemd"
systemd_networkd_nsswitch_group: "files systemd"
systemd_networkd_nsswitch_shadow: "files systemd"
systemd_networkd_nsswitch_gshadow: "files systemd"
systemd_networkd_nsswitch_hosts: "files resolve [!UNAVAIL=return] myhostname dns"
systemd_networkd_nsswitch_networks: "files dns"
systemd_networkd_nsswitch_protocols: "files"
systemd_networkd_nsswitch_services: "files"
systemd_networkd_nsswitch_ethers: "files"
systemd_networkd_nsswitch_rpc: "files"
systemd_networkd_nsswitch_netgroup: "nis"
systemd_networkd_nsswitch_automount: "files"
systemd_networkd_nsswitch_aliases: "files"
systemd_networkd_nsswitch_publickey: "files"
